# Provision an EC2 instance
template:
  type: "http"
  url: "https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.2.7/managed-ec2-linux-v1.j2"
stack_name: "belltown-solly-2019"
stack_tags:
  Department: "SysBio"
  Project: "amp-ad"
  OwnerEmail: "solly.sieberts@sagebase.org"
  CostCenter: "NIA AMP-AD CC / 101500"
sceptre_user_data:
  Distro: "ubuntu"     # (valid values: aws, ubuntu) AMIId must match distro
  # (Optional) Expose ports to incoming traffic (default is no open ports) (valid range: 1-65535)
  # OpenPorts: ["80","443"]
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "SysBio"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "amp-ad"
  # The resource owner
  OwnerEmail: "solly.sieberts@sagebase.org"

  # Default account settings, leave alone unless you plan to override
  VpcName: "computevpc"
  KeyName: "scicomp"
  AMIId: "ami-070b9bc1c83981407"      # Ubuntu 18, includes 2 data volumes

  # Settings have default values but can be overriden. Set the below
  # parameters *only* if you want to override the defaults.

  # (Optional) EC2 instance type, default is "t2.nano" (other available types https://aws.amazon.com/ec2/pricing/on-demand/)
  InstanceType: "r5.8xlarge"
  # (Optional) EC2 boot volume size in GB, default is 8GB, Max is 1000GB
  VolumeSize: "64"
  # (Optional) Run EC2 in a subnet (default: PrivateSubnet) (valid values: PrivateSubnet or PublicSubnet)
  # VpcSubnet: "PublicSubnet"
  # (Optional) Set true to enable daily backups (default: false)
  # BackupEc2: "true"
  # (Optional) Number of daily backups to keep (default: 7) (valid range: 1-180)
  # SnapshotCount: "14"

  # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm "/infra/JcConnectKey"
  JcServiceApiKey: !ssm "/infra/JcServiceApiKey"
  JcSystemsGroupId: !ssm "/infra/JcSystemsGroupId"
