template:
  type: "http"
  url: "https://ecmonsen-emorypipeline-ci-lambdaartifactsbucket-jnlt9zs4haa7.s3.amazonaws.com/lambda-uploader/v1.0.3/ecmonsen-emorypipeline-lambda.yaml"
# Note stack name must be 43 chars or less, otherwise bucket name is too long and CloudFormation fails
stack_name: "ecmonsen-emorypipeline-lambda"
stack_tags:
  OwnerEmail: "abby.vanderlinden@sagebase.org"
  CostCenter: "NIA AMP-AD CC / 101500"
dependencies:
  - "prod/ecmonsen-emorypipeline-ci.yaml"
parameters:
  # Source account is Emory University AWS account. Contact is Duc Duong
  SourceAccountId: "607721581289"
  SynapseStorageLocationId: "40934"
  # AMP-AD Sage Admin https://www.synapse.org/#!Team:3377637
  # Duc Duong https://www.synapse.org/#!Profile:3320325
  # Eva Monsen https://www.synapse.org/#!Profile:3399376
  # Tess Thyer https://www.synapse.org/#!Profile:3388489
  SynapseNotifyUsers: "3399376,3377637,3320325,3388489"
  Department: "SysBio"
  Project: "amp-ad"
  OwnerEmail: "tess.thyer@sagebase.org"
  SynapseUserName: "amp-ad-uploader"
