# Provision a Synapse External Bucket (http://docs.synapse.org/articles/custom_storage_location.html) that will
# work with the s3-synapse-sync lambda: https://github.com/Sage-Bionetworks/s3-synapse-sync
template:
  type: "http"
  url:  "https://raw.githubusercontent.com/Sage-Bionetworks/s3-synapse-sync/1.7.3/s3-synapse-sync-bucket.j2"
stack_name: "htan-dcc-center-a"
stack_tags:
  OwnerEmail: "adam.taylor@sagebase.org"
  CostCenter: "HTAN-DFCI / 120100"
dependencies:
  - "prod/s3-synapse-sync.yaml"
parameters:
  BucketName: "htan-dcc-center-a"  # must match bucket name in data/s3-synapse-sync-bucket-vars.yaml
  EnableDataLifeCycle: 'Enabled'
  LifecycleDataStorageClass: 'INTELLIGENT_TIERING'
  SynapseIDs:
    - "3382314"
    - "3408101"
    - "3413795"
  S3UserARNs:
    - "arn:aws:iam::070278699608:user/inodb"
    - "arn:aws:iam::728882028485:role/htan-project-TowerForgeBatchHeadJobRole-17MIZHWBA1TC5"
    - "arn:aws:iam::728882028485:role/htan-project-TowerForgeBatchWorkJobRole-17360PQARGWYU"
    - "arn:aws:sts::728882028485:assumed-role/AWSReservedSSO_TowerViewer_fd6aee98ec127705/adam.taylor@sagebase.org"
    - "arn:aws:iam::426577889437:user/bill.clifford"
  DenyDeleteARNs:
    - "arn:aws:iam::070278699608:user/inodb"
    - "arn:aws:iam::728882028485:role/htan-project-TowerForgeBatchHeadJobRole-17MIZHWBA1TC5"
    - "arn:aws:iam::728882028485:role/htan-project-TowerForgeBatchWorkJobRole-17360PQARGWYU"
    - "arn:aws:sts::728882028485:assumed-role/AWSReservedSSO_TowerViewer_fd6aee98ec127705/adam.taylor@sagebase.org"
    - "arn:aws:iam::426577889437:user/bill.clifford"
  S3AdminARNs:
    - "arn:aws:sts::526515999252:assumed-role/AWSReservedSSO_S3ExternalCollab_40c062f682e7f3f5/adam.taylor@sagebase.org"
    - "arn:aws:sts::526515999252:assumed-role/AWSReservedSSO_S3ExternalCollab_40c062f682e7f3f5/thomas.yu@sagebase.org"
  S3SynapseSyncFunctionArn: !stack_output_external "s3-synapse-sync::FunctionArn"
  S3SynapseSyncFunctionRoleArn: !stack_output_external "s3-synapse-sync::FunctionRoleArn"

# Due to circular dependencies, enabling bucket notification must be done after bucket creation
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig.html
sceptre_user_data:
  EnableNotificationConfiguration: "true"
