# Provision a Synapse External Bucket (http://docs.synapse.org/articles/custom_storage_location.html) that will
# work with the s3-synapse-sync lambda: https://github.com/Sage-Bionetworks/s3-synapse-sync
template_path: "htan-synapse-bucket.yaml"
stack_name: "htan-bucket-a"
stack_tags:
  Department: "CompOnc"
  Project: "HTAN"
  OwnerEmail: "xengie.doan@sagebase.org"
dependencies:
  - "prod/s3-synapse-sync.yaml"
parameters:
  SynapseIDs:
    - "3382314"
    - "3408101"
  S3UserARNs:
    - "arn:aws:sts::563295687221:assumed-role/sandbox-developer/xengie.doan@sagebase.org'
    - "arn:aws:iam::426577889437:user/clarisse.lau"
  S3CanonicalUserId: "eab4436941f355ce866fcf7944db42020c385ad1f19df8a95704dc4d7552fa06"
  S3SynapseSyncFunctionRoleArn: !stack_output_external "s3-synapse-sync::FunctionRoleArn"
