# Provision a Synapse External Bucket (http://docs.synapse.org/articles/custom_storage_location.html) that will
# work with the s3-synapse-sync lambda: https://github.com/Sage-Bionetworks/s3-synapse-sync
template_path: "remote/s3-synapse-sync-bucket.j2"
stack_name: "htan-dcc-tma-tnp"
stack_tags:
  Department: "CompOnc"
  Project: "HTAN"
  OwnerEmail: "bruno.grande@sagebase.org"
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/s3-synapse-sync/v1.5.0/s3-synapse-sync-bucket.j2 --create-dirs -o templates/remote/s3-synapse-sync-bucket.j2"
dependencies:
  - "prod/s3-synapse-sync.yaml"
parameters:
  BucketName: "htan-dcc-tma-tnp"
  SynapseIDs:
    - "3391844" #htan dcc
    - "3413795" #service acct
  S3UserARNs:
    - "arn:aws:iam::696725769253:user/creason"
    - "arn:aws:iam::292075781285:user/jmuhlich"
    - "arn:aws:sts::563295687221:assumed-role/AWSReservedSSO_Developer_baa6fed639faf5e7/jason.hwee@sagebase.org"
    - "arn:aws:sts::563295687221:assumed-role/AWSReservedSSO_Developer_baa6fed639faf5e7/adam.taylor@sagebase.org"
  DenyDeleteARNs:
    - "arn:aws:iam::696725769253:user/creason"
    - "arn:aws:iam::292075781285:user/jmuhlich"
    - "arn:aws:sts::563295687221:assumed-role/AWSReservedSSO_Developer_baa6fed639faf5e7/jason.hwee@sagebase.org"
    - "arn:aws:sts::563295687221:assumed-role/AWSReservedSSO_Developer_baa6fed639faf5e7/adam.taylor@sagebase.org"
  S3AdminARNs:
    - "arn:aws:iam::426577889437:user/clarisse.lau"
    - "arn:aws:sts::563295687221:assumed-role/AWSReservedSSO_Developer_baa6fed639faf5e7/bruno.grande@sagebase.org"
  S3SynapseSyncFunctionArn: !stack_output_external "s3-synapse-sync::FunctionArn"
  S3SynapseSyncFunctionRoleArn: !stack_output_external "s3-synapse-sync::FunctionRoleArn"

# Due to circular dependencies, enabling bucket notification must be done after bucket creation
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig.html
sceptre_user_data:
  EnableNotificationConfiguration: "true"
