# Provision a general S3 bucket or a Synapse External Bucket
# http://docs.synapse.org/articles/custom_storage_location.html

# For use in the MEP-LINCS Synapse Project https://www.synapse.org/mep_lincs

template:
  type: "http"
  url: "https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.2.7/s3-bucket.yaml"
stack_name: "mep-lincs-s3"
stack_tags:
  OwnerEmail: "thomas.yu@sagebase.org"
  CostCenter: "No Program / 000000"
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "SysBio"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "MEP-LINCS"
  # The resource owner
  OwnerEmail: "thomas.yu@sagebase.org"
  # (Optional) true for read-write bucket, false (default) for read-only bucket
  AllowWriteBucket: 'true'
  SynapseUserName: 'larssono'
  GrantAccess:
    - 'arn:aws:iam::325565585839:root'   # Required
  EnableDataLifeCycle: "Enabled"
  LifecycleDataStorageClass: "INTELLIGENT_TIERING"
