# Provision an EC2 instance
template_path: templates/managed-ec2.yaml
stack_name: mpnst-analysis
dependencies:
  - peer-vpn-computevpc
parameters:
  # The Sage deparment for this resource
  Department: "Computational Oncology"
  # The Sage project this resource will be used for
  Project: "NTAP"
  # The resource owner
  OwnerEmail: "xindi.guo@sagebase.org"
  AMIId: "ami-0c031218cbaf1204f"
  # EC2 instance type (available types https://aws.amazon.com/ec2/instance-types/)
  InstanceType: "t2.large"
  
  # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId
hooks:
  after_create:
    - !notify_ec2