# Provision an EC2 instance
template_path: templates/managed-ec2-v3.yaml
stack_name: tesla-ec2-500G
parameters:
  # The Sage deparment for this resource
  Department: "CompOnc"
  # The Sage project this resource will be used for
  Project: "TESLA"
  # The resource owner
  OwnerEmail: "xengie.doan@sagebase.org"
  # (Optional) EC2 instance type, default is "t2.nano" (other available types https://aws.amazon.com/ec2/instance-types/)
  InstanceType: "c5n.9xlarge"
  # (Optional) EC2 boot volume size in GB, default is 8GB, Max is 1000GB
  VolumeSize: "500"

  # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId
hooks:
  after_create:
    - !notify_ec2
