# For storage of files related to usage statistics reporting
template:
  type: "http"
  url: "https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.6.7/templates/S3/synapse-external-bucket.j2"
stack_name: "usage-statistics-S3"
stack_tags:
  Department: "SysBio"
  Project: "DataEngineering"
  OwnerEmail: 'larsson.omberg@sagebase.org'
  CostCenter: "NO PROGRAM / 000000"

parameters:
  GrantAccess:
    - 'arn:aws:sts::526515999252:assumed-role/AWSReservedSSO_S3ExternalCollab_40c062f682e7f3f5/phil.snyder@sagebase.org'
    - 'arn:aws:sts::526515999252:assumed-role/AWSReservedSSO_S3ExternalCollab_40c062f682e7f3f5/larsson.omberg@sagebase.org'
    - 'arn:aws:sts::526515999252:assumed-role/AWSReservedSSO_S3ExternalCollab_40c062f682e7f3f5/abby.vanderlinden@sagebase.org'

  # The following parameters are only examples they are not required.
  # You may omit them if you do not need to override the defaults.

  # (Optional) true for read-write bucket, false (default) for read-only bucket
  AllowWriteBucket: 'true'
