# Provision a general S3 bucket or a Synapse External Bucket
# http://docs.synapse.org/articles/custom_storage_location.html
template:
  type: "http"
  url: "https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.2.7/s3-bucket.yaml"
stack_name: "veoibd-s3"
stack_tags:
  OwnerEmail: "thomas.yu@sagebase.org"
  CostCenter: "No Program / 000000"
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "SysBio"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "VEO-IBD"
  # The resource owner
  OwnerEmail: "thomas.yu@sagebase.org"
  # (Optional) true for read-write bucket, false (default) for read-only bucket
  AllowWriteBucket: 'true'

  # Settings have default values but can be overriden. Set the below
  # parameters *only* if you want to override the defaults.

  # (Optional) Synapse username (default ""), required if AllowWriteBucket=true
  SynapseUserName: 'veoibd-admin'
  # (Optional) Allow accounts, groups, and users to access bucket. (default is no access).
  GrantAccess:
    - 'arn:aws:iam::325565585839:root'   # Required ARN for a synapse bucket
    - 'arn:aws:sts::526515999252:assumed-role/AWSReservedSSO_S3ExternalCollab_40c062f682e7f3f5/thomas.yu@sagebase.org'

  # (Optional) true (default) to encrypt bucket, false for no encryption
  # EncryptBucket: 'false'
  # (Optional) 'Enabled' to enable bucket versioning, default is 'Suspended'
  # BucketVersioning: 'Enabled'
  # (Optional) 'Enabled' to enable bucket data life cycle rule, default is 'Disabled'
  EnableDataLifeCycle: "Enabled"
  # (Optional) S3 bucket objects will transition into this storage class: GLACIER(default), DEEP_ARCHIVE, INTELLIGENT_TIERING, STANDARD_IA, ONEZONE_IA
  LifecycleDataStorageClass: "INTELLIGENT_TIERING"
  # (Optional) Number of days until S3 objects are moved to the LifecycleDataStorageClass, default is 30
  # LifecycleDataTransition: '90'
  # (Optional) Number of days (from creation) when objects are deleted from S3 and LifecycleDataStorageClass, default is 365000
  # LifecycleDataExpiration: '1825'
