project_code: sage-bionetworks
template_bucket_name: bootstrap-awss3cloudformationbucket-114n2ojlbvj21
template_key_prefix: {{ environment_variable.TRAVIS_BRANCH | default("testing") }}
admincentral_cf_bucket: "bootstrap-awss3cloudformationbucket-19qromfd235z9"
# Sender for notification hooks
aws_account_name: Scicomp
aws_account_email: aws.scicomp@sagebase.org
# Provisioner defaults
default_ami: "ami-082278746f893d99c"
default_key_pair: "scicomp"
default_vpc: "computevpc"
default_win_ami: "ami-0388ce15d3f7066cb"
default_ubuntu_ami: "ami-0618d7bfcc5a707aa"
